### ISSUE TITLE
Result reproduction

### ISSUE THREAD

**Issue by jocelyn2002** [ipolharvard/ethos-paper#9]
Hello! I tried to reproduce the result in your paper. I didn't train the model from scratch. Instead I download the trained model from gooogle drive. Other step are just like that described in ReadMe, but I found that my result is quite different from yours.
![image](https://github.com/user-attachments/assets/dafea120-7983-49d7-b69d-4ca0fb74b5d4)
My readimmission AUC is around 0.78, and the marks on the plot are much fewer than yours:
![image](https://github.com/user-attachments/assets/44f19500-9bd4-4dff-ae1e-9d74cde95a25)
I'm very confused. Could you tell me how can I solve the problem? I would appreciate it very much!

**Comment by prenc** [comment]
Hey @jocelyn2002, you need to repeat the inference several times since the model is zero-shot. In our paper, we use 20 repetitions to generate each outcome, and the ROC AUC is approximated based on the "marks." You can check the original results we published, where there are files with the suffix `_repN`, where N is the repetition number.

From the [paper](https://www.nature.com/articles/s41746-024-01235-0):
> The chance of inpatient mortality was assessed at the time of admission for all inpatient stays for patients in the test set unless the discharge day was unknown. This was performed by the generative process that began with the admission token and ended upon generating a discharge or death token, repeating this cycle 20 times. The ‘N’, representing the number of times a death token was generated first, was divided by 20 to estimate the chance of inpatient mortality.

Also, refer to [this script](https://github.com/ipolharvard/ethos-paper/blob/master/scripts/run_inference.sh) for more information.

**Comment by jocelyn2002** [comment]
Thank you so much! I'll try to repeat the experiment.
